version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    networks:
      - internal
    volumes:
      - ./config:/srv/config
      - ./app:/srv/app
    env_file:
      - .env
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_JOBS_ALIVE_PRICE_SYMBOL=BTCUSDT
      - BINANCE_JOBS_ALIVE_BALANCE_SYMBOLS=BTC,USDT
      - BINANCE_JOBS_BBANDS_SYMBOL=BTCUSDT
      - BINANCE_JOBS_MACD_STOP_CHASER_SYMBOL=BTCUSDT
      - REDIS_HOST=binance-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  binance-redis:
    container_name: binance-redis
    image: redis:6.0
    networks:
      - internal
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

networks:
  internal:
    driver: bridge

volumes:
  redis_data:
