version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    image: chrisleekr/binance-trading-bot:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8080:80
      - 8081:81
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_SLACK_ENABLED=true
      - BINANCE_JOBS_ALIVE_ENABLED=true
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_ENABLED=true
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_CANDLES_INTERVAL=15m
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_CANDLES_LIMIT=200
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_SYMBOLS=["BTCUPUSDT", "ETHUPUSDT",
        "LINKUPUSDT", "DOTUPUSDT", "ADAUPUSDT", "LTCUPUSDT", "XRPUPUSDT",
        "BNBUPUSDT", "TRXUPUSDT", "XLMUPUSDT"]
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_MAX_PURCHASE_AMOUNT=100
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_LAST_BUY_PERCENTAGE=1.06
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_STOP_PERCENTAGE=0.97
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_LIMIT_PERCENTAGE=0.969
      - REDIS_HOST=binance-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  binance-redis:
    container_name: binance-redis
    image: redis:6.0
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

networks:
  internal:
    driver: bridge

volumes:
  redis_data:
