version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    image: chrisleekr/binance-trading-bot:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_SLACK_ENABLED=true - BINANCE_JOBS_SIMPLE_STOP_CHASER_ENABLED=true
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_SYMBOLS=["BTCUSDT", "ETHUSDT", "LTCUSDT", "XRPUSDT", "LINKUSDT", "BNBUSDT", "EOSUSDT", "TRXUSDT", "XLMUSDT", "BCHUSDT", "DOTUSDT", "ADAUSDT"]
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_CANDLES_LIMIT=100
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_CANDLES_INTERVAL=1h
      - REDIS_HOST=binance-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  binance-redis:
    container_name: binance-redis
    image: redis:6.0
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - redis_data:/data

networks:
  internal:
    driver: bridge

volumes:
  redis_data:
