version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    build:
      context: ./
      target: dev-stage
      # target: production-stage
    networks:
      - internal
    volumes:
      - ./config:/srv/config
      - ./app:/srv/app
      - ./public:/srv/public
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8080:80
      - 8081:81
    environment:
      - BINANCE_MODE=test
      # - BINANCE_MODE=live
      - BINANCE_JOBS_ALIVE_ENABLED=true
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_ENABLED=true
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_SYMBOLS=["BTCUSDT", "ETHUSDT",
        "LTCUSDT", "XRPUSDT", "BNBUSDT"]
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_LAST_BUY_PERCENTAGE=1.01
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_STOP_PERCENTAGE=0.99
      - BINANCE_JOBS_SIMPLE_STOP_CHASER_STOP_LOSS_LIMIT_LIMIT_PERCENTAGE=0.98
      - REDIS_HOST=binance-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  binance-redis:
    container_name: binance-redis
    image: redis:6.0
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

networks:
  internal:
    driver: bridge

volumes:
  redis_data:
