name: Bump versions

on: [workflow_dispatch]

jobs:
  bump-versions:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Bump Version (Patch)
        if:
          github.repository == 'chrisleekr/binance-trading-bot' && github.ref ==
          'refs/heads/master'
        run: |
          git config --global user.email ${{ secrets.GIT_CI_EMAIL }}
          git config --global user.name ${{ secrets.GIT_CI_NAME }}
          PACKAGE_VERSION=$(npm version patch -m "Update version to %s [skip ci]")
          git status
          git push https://${{ secrets.GIT_CI_USERNAME }}:${{ secrets.GIT_CI_PASSWORD }}@${{ secrets.GIT_REPO_DOMAIN }}/chrisleekr/binance-trading-bot.git HEAD:$GITHUB_REF
          git push https://${{ secrets.GIT_CI_USERNAME }}:${{ secrets.GIT_CI_PASSWORD }}@${{ secrets.GIT_REPO_DOMAIN }}/chrisleekr/binance-trading-bot.git $PACKAGE_VERSION
